### ISSUE TITLE
各种报错

### ISSUE THREAD

**Issue by icloudnote** [wzyonggege/clean_blog#1]
你这边能验证一下python的版本和各个软件包的版本吗？既然将代码放到了github上面，就要对他人负责，我这边尝试了一下，各种报错。。。

**Comment by afacode** [comment]
部署的时候集静态文件时  python manage.py collectstatic   
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/afa/blog.afacode.top/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/xadmin/__init__.py", line 4, in <module>
    from xadmin.sites import AdminSite, site
  File "/home/afa/blog.afacode.top/env/lib/python3.4/site-packages/xadmin/sites.py", line 9, in <module>
    reload(sys)
NameError: name 'reload' is not defined
是我的python版本太低了吗

**Comment by febritecno** [comment]
same

**Comment by QaZqwefgh** [comment]
blog 0001_initial is not exist!   大神 能整理下給個開箱即用的版本啊

**Comment by realei** [comment]
same
